server:
  port: 8080
  ssl:
    enabled: false
    key-store: 
    key-store-password: 
    key-store-type: 
    trust-store: 
    trust-store-password: 
    trust-store-type: 

jwt:
  secret: my-super-secret-key-my-super-secret-key

spring:

  application:
    name: gateway-auth-app

  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      server:
        webmvc:

          routes:

            - id: sign-service
              uri: http://localhost:9001
              predicates:
                - Path=/api/sign/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
        
        
my-app:
  proxy:
    enabled: false
    #host: proxy.yourcompany.com
    #port: 8080
    user: proxyuser
    password: proxypassword